### ISSUE TITLE
Failed to load ressources

### ISSUE THREAD

**Issue by raf4e7** [itop-itsm-ru/dashlet-calendar#1]
Hi vbkunin !

I'm very interested in your dashlet calendar extension and I try to install it in my iTop dev environement.
I follow all the steps as you say in the Readme file but I'm unable to display the calendar.
When I display the page, nothing appears and the Chrome inspector tool log theses errors ::
```
- custom.css : Failed to load resource: the server responded with a status of 404 (Not Found)

- moment.min.js : Failed to load resource: the server responded with a status of 404 (Not Found)

- fullcalendar.min.css : Failed to load resource: the server responded with a status of 404 (Not Found)

- fullcalendar.min.js : Failed to load resource: the server responded with a status of 404 (Not Found)

- moment.min.js : Failed to load resource: the server responded with a status of 404 (Not Found)
fullcalendar.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

- UI.php?c[menu]=ConfigManagementOverview:1 : Unsafe attempt to load URL data:image/svg+xml;utf8,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' height='0'><filter id='greyscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0' /></filter></svg>#greyscale from frame with URL http://localhost/pages/UI.php?c%5Bmenu%5D=ConfigManagementOverview. Domains, protocols and ports must match.

- data:0 : Failed to load resource: net::ERR_INVALID_URL
2timetable32.png Failed to load resource: the server responded with a status of 404 (Not Found)
UI.php?c[menu]=ConfigManagementOverview:3 Uncaught TypeError: $(...).fullCalendar is not a function
    at eval (eval at <anonymous> (jquery-1.10.0.min.js?itopversion=2.3.3:4), <anonymous>:3:39)
    at eval (<anonymous>)
    at jquery-1.10.0.min.js?itopversion=2.3.3:4
    at Function.globalEval (jquery-1.10.0.min.js?itopversion=2.3.3:4)
    at e.fn.init.domManip (jquery-1.10.0.min.js?itopversion=2.3.3:5)
    at e.fn.init.append (jquery-1.10.0.min.js?itopversion=2.3.3:5)
    at e.fn.init.<anonymous> (jquery-1.10.0.min.js?itopversion=2.3.3:5)
    at Function.access (jquery-1.10.0.min.js?itopversion=2.3.3:4)
    at e.fn.init.html (jquery-1.10.0.min.js?itopversion=2.3.3:5)
    at Object.success (dashboard.js?itopversion=2.3.3:323)

- custom.css : Failed to load resource: the server responded with a status of 404 (Not Found)
fullcalendar.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
```
I installed and use a lot of others extensions (or my own ones) without problems. Any idea to help me ?

Thanks a lot for your work :)

Rafael.

**Comment by vbkunin** [comment]
Hi Rafael!
You haven't forgotten to rename module folder to "dashlet-calendar", have you?)
Please check the path (in chrome inspector, network tab) from which your browser tries to get the module files. It should be like that:
http://your-itop-host-name/env-production/dashlet-calendar/fullcalendar/fullcalendar.min.js
Then check that you actually have /var/www/env-production/dashlet-calendar folder and files are inside.

P.S. These two errors are not mine :)
- UI.php?c[menu]=ConfigManagementOverview:1 : Unsafe attempt to load URL...
- data:0 : Failed to load resource: net::ERR_INVALID_URL

**Comment by raf4e7** [comment]
Hi Vladimir!
Thanks to your answer.
You're right !!! My extension folder was named "dashlet-calendar-master". I
rename it and it works fine now!

Thanks a lot again

Rafael, your user from France ! ;)

2017-03-22 21:46 GMT+01:00 Vladimir Kunin <notifications@github.com>:

**Comment by vbkunin** [comment]
I was glad to help you, Rafael!)
