### ISSUE TITLE
Unfinished events

### ISSUE THREAD

**Issue by javiergarces1969** [itop-itsm-ru/dashlet-calendar#3]
Hello

I'm testing the option 'Unfinished events' with user requests, incidents and problems but I can't get that it to work as I' ve understood that it should work.

For example, I've edited the Welcome page and created a calendar to show the user requests. If I check the 'Unfinished events' option, then, the calendar is filled until the present day and when I uncheck the option, the calendar is not filled This is ok.

However, when I save the dashboard page with the unchecked option, then the calendar behavior is as if the option is checked although it is not. This also happens with incidents and problemas

I'm using itop 2.3.4 with PHP 5.5

Thanks

**Comment by vbkunin** [comment]
Hello @javiergarces1969,
It's a bug of course. Thank you for the issue!
