### ISSUE TITLE
dashlet-calender extension is not working with iTOP 2.5

### ISSUE THREAD

**Issue by MonaMZ** [itop-itsm-ru/dashlet-calendar#4]
Hello,
This extension is working well for me in ITOP 2.4, but when i switched to ITOP 2.5 (cause I need some new features from this release) dashlet calendar is no more displaying events... when I inspect page I found this error :
 Uncaught Error: Call to undefined method stdClass::GetClassAlias() in C:\xampp\htdocs\ITOPnew\env-production\dashlet-calendar\ajax.php:18
Stack trace:
#0 {main}
  thrown in <b>C:\xampp\htdocs\ITOPnew\env-production\dashlet-calendar\ajax.php

Thanks in advance for your help
Mona

**Comment by MonaMZ** [comment]
any help please on this issue

**Comment by vbkunin** [comment]
Hi @MonaMZ, I just fixed it.

**Comment by MonaMZ** [comment]
Thanks a lot it works
